cc_test(
    name = "mutex_test",
    srcs = ["mutex_test.cc"],
    deps = [
        "//thread:mutex",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "threadsafequeue_test",
    srcs = ["threadsafequeue_test.cc"],
    deps = [
        "//thread:threadsafequeue",
        "@googletest//:gtest_main",
    ],
)
